#!/bin/bash

. ubiquitous_bash.sh

mkdir -p "$(getScriptAbsoluteFolder)/TazStiff_Config/.Slic3r"

#proot -b "$(getScriptAbsoluteFolder)/TazStiff_Config/.Slic3r:"$HOME"/.Slic3r" "$(getScriptAbsoluteFolder)/Slic3r/binary/x86/1-2-9/bin/slic3r"

#Repository Version
proot -b "$(getScriptAbsoluteFolder)/TazStiff_Config/.Slic3r:"$HOME"/.Slic3r" "$(which slic3r.pl)"
